name: video_spliter
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.1+18

environment:
  sdk: ^3.7.0

dependencies:
  animated_digit: ^3.2.3
  clarity_flutter: ^1.0.0
  cupertino_icons: ^1.0.8
  ffmpeg_kit_flutter_new: ^1.2.1
  file_picker: ^10.1.9
  # firebase_app_distribution: ^1.1.1
  firebase_analytics: ^11.4.6
  firebase_core: ^3.13.1
  firebase_messaging: ^15.2.6
  firebase_storage: ^12.4.7
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_local_notifications: ^18.0.0
  flutter_localizations:
    sdk: flutter
  flutter_sharing_intent: ^1.1.1
  get: ^4.7.2
  google_fonts: ^6.2.1
  google_mobile_ads: ^6.0.0
  image_picker: ^1.1.2
  in_app_review: ^2.0.10
  intl: ^0.20.2
  lottie: ^3.3.1
  package_info_plus: ^8.3.0
  path: ^1.8.3
  path_provider: ^2.0.13
  percent_indicator: ^4.2.5
  permission_handler: ^11.3.1
  # receive_sharing_intent: ^1.4.5
  share_plus: ^11.0.0
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.2
  video_player: ^2.9.5

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  rxdart: ^0.28.0


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/intro/
    - assets/logo/
    - assets/animations/
